# Generated by Django 4.2.7 on 2023-11-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_images_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='brand_images/'),
        ),
    ]
